### ISSUE TITLE
Ctrl|Cmd + F1 doesn't work.

### ISSUE THREAD

**Issue by Hussain08** [DracotMolver/CSS-minify#1]
Tried [ Ctrl|Cmd + F1 ] on  VS Code 1.14.2 and didn't work. But when clicked only F1 it let me to write css minify.

**Comment by DracotMolver** [comment]
Oooh i will update the info, because it is my mistake. I was using a laptop assuming that everybody had to typed the same thing. Thanks a lot 😊
