### ISSUE TITLE
Space removed before "[" and after "]"

### ISSUE THREAD

**Issue by CharlieEtienne** [DracotMolver/CSS-minify#10]
Hi @DracotMolver , it's me again ;)

I experienced another bug:

`.my-form[disabled=true] .my-input {
  cursor: not-allowed;
}`

is minified as:

`.my-form[disabled=true].my-input{cursor:not-allowed;}`

removing space between attribute value selector (`[disabled=true]`) and children class (`.my-input`)

As well as 
`.accordion [data-toggle='collapse']`
is minified as 
`.accordion[data-toggle='collapse']`

**Comment by CharlieEtienne** [comment]
Maybe you should avoid to remove spaces from selectors, I don't know if there's some cases where it's useful...

**Comment by DracotMolver** [comment]
You are absolutely right. Even if i use the tag name, you will be working well on your normal css file. That means, you will do the next things:
`.accordion [data-toggle='collapse']`
`span[data-toggle='collapse']`
So, yes. There's no point to do it :). Thanks a lot @CharlieEtienne, I'll change the mock and the regex as soon as possible 👍
