### ISSUE TITLE
Space after :not

### ISSUE THREAD

**Issue by ControlledChaos** [DracotMolver/CSS-minify#11]
I have found that the minify process is eliminating spaces following a :not property. For instance: `body:not(.logged-in) .greeting` becomes `body:not(.logged-in).greeting`, thereby breaking the assigned values.

**Comment by DracotMolver** [comment]
thanks for this. I know it's been a while but i will fix it as soon as possible :)

**Comment by ControlledChaos** [comment]
Great, thank you. Have a good holiday season.

**Comment by DracotMolver** [comment]
The issue was fixed now. Thanks a lot again :+1:

**Comment by ControlledChaos** [comment]
Excellent!
