### ISSUE TITLE
improve your vscode docs

### ISSUE THREAD

**Issue by ashadnasim52** [DracotMolver/CSS-minify#14]
please improve your vs code docs as in list it makes someone confuse 
<br />
![image](https://user-images.githubusercontent.com/38835999/66262795-26814f80-e805-11e9-9a5b-c02cadf39943.png)

it just simple error but can let beginner not understand your extension

**Comment by DracotMolver** [comment]
Hi @ashadnasim52  No problem. You're right that might confuse people. I'll improve it.
