### ISSUE TITLE
Converting "none" and "unset" to "0"

### ISSUE THREAD

**Issue by ControlledChaos** [DracotMolver/CSS-minify#4]
CSS-minify has very recently started converting properties such as `display: none` to `display: 0` and `clip-path: unset` to `clip-path: 0`. This renders the styles void, hence they are ignored by the browser.

**Comment by DracotMolver** [comment]
My BIG mistake!. So sorry if that screw up your file. I will fixe it as soon as possible. Thanks a lot for had reported the issue

**Comment by ControlledChaos** [comment]
No problem. Thanks for building such a handy tool!

**Comment by digilou** [comment]
@DracotMolver It also converts `none` value of `list-style-type` to 0.

**Comment by DracotMolver** [comment]
This was something really lazy and dummy that i did. By now don't use the extension. As soon I got home after work I fix this issue 😅

**Comment by DracotMolver** [comment]
The issue was fix and they were added as cases on the tests. Thanks a lot @ControlledChaos  and @digilou

**Comment by digilou** [comment]
Quick turnaround! You’re amazing @dracotmolver!
