### ISSUE TITLE
Removing quotes from font formats

### ISSUE THREAD

**Issue by jas-naz** [DracotMolver/CSS-minify#5]
The minifying is removing quotes from the font format, so
```
@font-face{
   font-family:'pxgrotesk-regular';
   src:url('pxgrotesk-regular.eot');
   src:url('pxgrotesk-regular.eot?#iefix') format('embedded-opentype'), 
   url('pxgrotesk-regular.woff2') format('woff2'), 
   url('pxgrotesk-regular.woff') format('woff'), 
   url('pxgrotesk-regular.ttf') format('truetype'), 
   url('pxgrotesk-regular.svg#svgFontName') format('svg');
}
```
becomes
```
@font-face{
   font-family:'pxgrotesk-regular';
   src:url(pxgrotesk-regular.eot);
   src:url(pxgrotesk-regular.eot?#iefix) format(embedded-opentype), 
   url(pxgrotesk-regular.woff2') format(woff2), 
   url(pxgrotesk-regular.woff') format(woff), 
   url(pxgrotesk-regular.ttf') format(truetype), 
   url(pxgrotesk-regular.svg#svgFontName) format(svg);
}
```
Then the browser[chrome] isn't rendering correctly, if I add quotes back to jus the format() it fixes it.

Thanks for your extension.

**Comment by DracotMolver** [comment]
@jas-naz thanks you for had reported this issue. I can see where is my mistake. I'll fix it into a few hours :smile:. Your case and example is really good to use it as a test to run against with

**Comment by DracotMolver** [comment]
The issue was fixed and I added it as a testing case :smile:. Thanks a lot again :+1:

**Comment by jas-naz** [comment]
Thanks for the quick turnaround, however, I found another one, I will create a new issue for it.
