### ISSUE TITLE
Missing space before asterisk selector

### ISSUE THREAD

**Issue by jas-naz** [DracotMolver/CSS-minify#6]
It is removing the space infront of an asterisk when used as a global selector.
```
#aptApp * { 
   box-sizing: content-box;
}
```
becomes

`#aptApp*{box-sizing:content-box;}`

which failes as a selector it was intended for.

expected
`#aptApp *{box-sizing:content-box;}`

**Comment by DracotMolver** [comment]
you read my mind!. I was thinking today, while I was fixing the other issue, that this case I haven't tested it. I should have done it :disappointed:

**Comment by DracotMolver** [comment]
Fixed it :smile:. Thanks a lot again :+1:

**Comment by jas-naz** [comment]
I've confirmed this fix in my source. Thanks again.

**Comment by DracotMolver** [comment]
Awesome!. So glad to read it
