### ISSUE TITLE
Add spaces in some URLs

### ISSUE THREAD

**Issue by CharlieEtienne** [DracotMolver/CSS-minify#7]
# Example : 
## In _style.css_ : 
`@import url("//fonts.googleapis.com/css?family=Maven+Pro:400,500,700,900");`

## In _style.min.css_ : 
`@import url("//fonts.googleapis.com/css?family=Maven + Pro:400,500,700,900");`

# Issue : 
There are some spaces before and after the "**+**" symbol in the minified url.
It produces bugs like 404 errors.

**Comment by DracotMolver** [comment]
@CharlieEtienne Thanks a lot for had reported this. This case wasn't tested, so thanks a lot for this. Now the issue is fixed :smile:
