### ISSUE TITLE
Media query not working after minification

### ISSUE THREAD

**Issue by itimgit** [DracotMolver/CSS-minify#8]
@media only screen and (min-width: 375px) is being minified as
@media only screen and(min-width:375px)
The space between 'and' and '(' is needed for the query to work.

**Comment by DracotMolver** [comment]
Ouch, big mistake. I'll fix t as soon as I get home :smile:. Thanks a lot for had reported it

**Comment by itimgit** [comment]
No problem, thanks for creating the extension!

**Comment by DracotMolver** [comment]
Thanks you for the feedback :smile:.
