### ISSUE TITLE
Space removed in CSS width: calc() rules

### ISSUE THREAD

**Issue by CharlieEtienne** [DracotMolver/CSS-minify#9]
### This rule:
`.grid-item {
  width: calc((100% / 3) - 20px);
}`

### gives:
`.grid-item{width:calc((100% / 3)- 20px)}`

### Result: the rule doesn't work anymore because space before minus is removed.

**Comment by DracotMolver** [comment]
Hi @CharlieEtienne. Thanks a lot for reporting this. I'll fix it as soon as possible :relaxed:

**Comment by DracotMolver** [comment]
The issue was fixed. Thanks a lot! :+1:

**Comment by CharlieEtienne** [comment]
@DracotMolver Sorry, but the fix didn't work in my case... 
It stills minify to `.grid-item{width:calc((100% / 3)- 20px)}`...

I think in [fix 93541c5](https://github.com/DracotMolver/CSS-minify/commit/93541c5eb01204e502ba0623414b870cc8e66ed1) you only care about the "+" symbol ; my problem was with the "-" symbol...

**Comment by DracotMolver** [comment]
ooh I see. It's my fault of course, I'll do a better regex and a proper test. Thanks :smiley:

**Comment by DracotMolver** [comment]
@CharlieEtienne I fixed the issue. It should work well now.
If you are using calc, I'll check for the next symbols: `+`, `-`, `*`, `/`. I added your example on the mock that I use to test the code :). Thanks a lot!
